#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 78
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 86
#define ALIAS_COUNT 0
#define TOKEN_COUNT 60
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 25
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 21

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_EQ = 3,
  anon_sym_malloc = 4,
  anon_sym_LPAREN = 5,
  anon_sym_COMMA = 6,
  anon_sym_RPAREN = 7,
  anon_sym_free = 8,
  anon_sym_overflow = 9,
  anon_sym_expansion = 10,
  anon_sym_swap = 11,
  anon_sym_may = 12,
  anon_sym_must = 13,
  anon_sym_min = 14,
  anon_sym_max = 15,
  anon_sym_LT = 16,
  anon_sym_DASH1 = 17,
  anon_sym_0 = 18,
  anon_sym_1 = 19,
  anon_sym_2 = 20,
  anon_sym_3 = 21,
  anon_sym_4 = 22,
  anon_sym_5 = 23,
  anon_sym_6 = 24,
  anon_sym_7 = 25,
  anon_sym_8 = 26,
  anon_sym_9 = 27,
  anon_sym_GT = 28,
  anon_sym_DOT = 29,
  anon_sym_size = 30,
  anon_sym_strlen = 31,
  anon_sym_begin = 32,
  anon_sym_end = 33,
  anon_sym_field = 34,
  anon_sym_PIPE_PIPE = 35,
  anon_sym_MAX = 36,
  anon_sym_MIN = 37,
  anon_sym_EOF = 38,
  anon_sym_NULL = 39,
  anon_sym_UNDEF = 40,
  anon_sym_NPOS = 41,
  anon_sym_a = 42,
  anon_sym_b = 43,
  anon_sym_c = 44,
  anon_sym_d = 45,
  anon_sym_e = 46,
  anon_sym_f = 47,
  anon_sym_A = 48,
  anon_sym_B = 49,
  anon_sym_C = 50,
  anon_sym_D = 51,
  anon_sym_E = 52,
  anon_sym_F = 53,
  anon_sym_PLUS = 54,
  anon_sym_DASH = 55,
  anon_sym_STAR = 56,
  anon_sym_SLASH = 57,
  anon_sym_LBRACK = 58,
  anon_sym_RBRACK = 59,
  sym_source_file = 60,
  sym_memory_summary = 61,
  sym_side_effects = 62,
  sym_memory_side_effect = 63,
  sym_assign = 64,
  sym_malloc = 65,
  sym_free = 66,
  sym_overflow = 67,
  sym_expansion = 68,
  sym_swap = 69,
  sym_possibility = 70,
  sym_object = 71,
  sym_overflow_arg = 72,
  sym_overflow_func = 73,
  sym_key = 74,
  sym_key_attribute = 75,
  sym_attribute = 76,
  sym_values = 77,
  sym_value = 78,
  sym_single_value = 79,
  sym_constant_value = 80,
  sym_number = 81,
  sym_alpha = 82,
  sym_binary_expr = 83,
  sym_range_value = 84,
  aux_sym_side_effects_repeat1 = 85,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_malloc] = "malloc",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_free] = "free",
  [anon_sym_overflow] = "overflow",
  [anon_sym_expansion] = "expansion",
  [anon_sym_swap] = "swap",
  [anon_sym_may] = "may",
  [anon_sym_must] = "must",
  [anon_sym_min] = "min",
  [anon_sym_max] = "max",
  [anon_sym_LT] = "<",
  [anon_sym_DASH1] = "-1",
  [anon_sym_0] = "0",
  [anon_sym_1] = "1",
  [anon_sym_2] = "2",
  [anon_sym_3] = "3",
  [anon_sym_4] = "4",
  [anon_sym_5] = "5",
  [anon_sym_6] = "6",
  [anon_sym_7] = "7",
  [anon_sym_8] = "8",
  [anon_sym_9] = "9",
  [anon_sym_GT] = ">",
  [anon_sym_DOT] = ".",
  [anon_sym_size] = "size",
  [anon_sym_strlen] = "strlen",
  [anon_sym_begin] = "begin",
  [anon_sym_end] = "end",
  [anon_sym_field] = "field",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_MAX] = "MAX",
  [anon_sym_MIN] = "MIN",
  [anon_sym_EOF] = "EOF",
  [anon_sym_NULL] = "NULL",
  [anon_sym_UNDEF] = "UNDEF",
  [anon_sym_NPOS] = "NPOS",
  [anon_sym_a] = "a",
  [anon_sym_b] = "b",
  [anon_sym_c] = "c",
  [anon_sym_d] = "d",
  [anon_sym_e] = "e",
  [anon_sym_f] = "f",
  [anon_sym_A] = "A",
  [anon_sym_B] = "B",
  [anon_sym_C] = "C",
  [anon_sym_D] = "D",
  [anon_sym_E] = "E",
  [anon_sym_F] = "F",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym_memory_summary] = "memory_summary",
  [sym_side_effects] = "side_effects",
  [sym_memory_side_effect] = "memory_side_effect",
  [sym_assign] = "assign",
  [sym_malloc] = "malloc",
  [sym_free] = "free",
  [sym_overflow] = "overflow",
  [sym_expansion] = "expansion",
  [sym_swap] = "swap",
  [sym_possibility] = "possibility",
  [sym_object] = "object",
  [sym_overflow_arg] = "overflow_arg",
  [sym_overflow_func] = "overflow_func",
  [sym_key] = "key",
  [sym_key_attribute] = "key_attribute",
  [sym_attribute] = "attribute",
  [sym_values] = "values",
  [sym_value] = "value",
  [sym_single_value] = "single_value",
  [sym_constant_value] = "constant_value",
  [sym_number] = "number",
  [sym_alpha] = "alpha",
  [sym_binary_expr] = "binary_expr",
  [sym_range_value] = "range_value",
  [aux_sym_side_effects_repeat1] = "side_effects_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_malloc] = anon_sym_malloc,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_free] = anon_sym_free,
  [anon_sym_overflow] = anon_sym_overflow,
  [anon_sym_expansion] = anon_sym_expansion,
  [anon_sym_swap] = anon_sym_swap,
  [anon_sym_may] = anon_sym_may,
  [anon_sym_must] = anon_sym_must,
  [anon_sym_min] = anon_sym_min,
  [anon_sym_max] = anon_sym_max,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_DASH1] = anon_sym_DASH1,
  [anon_sym_0] = anon_sym_0,
  [anon_sym_1] = anon_sym_1,
  [anon_sym_2] = anon_sym_2,
  [anon_sym_3] = anon_sym_3,
  [anon_sym_4] = anon_sym_4,
  [anon_sym_5] = anon_sym_5,
  [anon_sym_6] = anon_sym_6,
  [anon_sym_7] = anon_sym_7,
  [anon_sym_8] = anon_sym_8,
  [anon_sym_9] = anon_sym_9,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_size] = anon_sym_size,
  [anon_sym_strlen] = anon_sym_strlen,
  [anon_sym_begin] = anon_sym_begin,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_field] = anon_sym_field,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_MAX] = anon_sym_MAX,
  [anon_sym_MIN] = anon_sym_MIN,
  [anon_sym_EOF] = anon_sym_EOF,
  [anon_sym_NULL] = anon_sym_NULL,
  [anon_sym_UNDEF] = anon_sym_UNDEF,
  [anon_sym_NPOS] = anon_sym_NPOS,
  [anon_sym_a] = anon_sym_a,
  [anon_sym_b] = anon_sym_b,
  [anon_sym_c] = anon_sym_c,
  [anon_sym_d] = anon_sym_d,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_f] = anon_sym_f,
  [anon_sym_A] = anon_sym_A,
  [anon_sym_B] = anon_sym_B,
  [anon_sym_C] = anon_sym_C,
  [anon_sym_D] = anon_sym_D,
  [anon_sym_E] = anon_sym_E,
  [anon_sym_F] = anon_sym_F,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym_memory_summary] = sym_memory_summary,
  [sym_side_effects] = sym_side_effects,
  [sym_memory_side_effect] = sym_memory_side_effect,
  [sym_assign] = sym_assign,
  [sym_malloc] = sym_malloc,
  [sym_free] = sym_free,
  [sym_overflow] = sym_overflow,
  [sym_expansion] = sym_expansion,
  [sym_swap] = sym_swap,
  [sym_possibility] = sym_possibility,
  [sym_object] = sym_object,
  [sym_overflow_arg] = sym_overflow_arg,
  [sym_overflow_func] = sym_overflow_func,
  [sym_key] = sym_key,
  [sym_key_attribute] = sym_key_attribute,
  [sym_attribute] = sym_attribute,
  [sym_values] = sym_values,
  [sym_value] = sym_value,
  [sym_single_value] = sym_single_value,
  [sym_constant_value] = sym_constant_value,
  [sym_number] = sym_number,
  [sym_alpha] = sym_alpha,
  [sym_binary_expr] = sym_binary_expr,
  [sym_range_value] = sym_range_value,
  [aux_sym_side_effects_repeat1] = aux_sym_side_effects_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_malloc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_free] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_overflow] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_expansion] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_swap] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_may] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_must] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_min] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_max] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_3] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_4] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_5] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_6] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_7] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_9] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_size] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_strlen] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_begin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_field] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MAX] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MIN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EOF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NULL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_UNDEF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NPOS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_a] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_c] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_d] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_A] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_B] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_C] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_D] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_F] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_memory_summary] = {
    .visible = true,
    .named = true,
  },
  [sym_side_effects] = {
    .visible = true,
    .named = true,
  },
  [sym_memory_side_effect] = {
    .visible = true,
    .named = true,
  },
  [sym_assign] = {
    .visible = true,
    .named = true,
  },
  [sym_malloc] = {
    .visible = true,
    .named = true,
  },
  [sym_free] = {
    .visible = true,
    .named = true,
  },
  [sym_overflow] = {
    .visible = true,
    .named = true,
  },
  [sym_expansion] = {
    .visible = true,
    .named = true,
  },
  [sym_swap] = {
    .visible = true,
    .named = true,
  },
  [sym_possibility] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_overflow_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_overflow_func] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_key_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_values] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_single_value] = {
    .visible = true,
    .named = true,
  },
  [sym_constant_value] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_alpha] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_range_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_side_effects_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_attribute = 1,
  field_close_angle = 2,
  field_close_paren = 3,
  field_comma = 4,
  field_constant_value = 5,
  field_dot = 6,
  field_func_name = 7,
  field_key = 8,
  field_key_attribute = 9,
  field_left = 10,
  field_may = 11,
  field_must = 12,
  field_number = 13,
  field_object = 14,
  field_open_angle = 15,
  field_open_paren = 16,
  field_operation = 17,
  field_operation_name = 18,
  field_operator = 19,
  field_or = 20,
  field_possibility = 21,
  field_range_value = 22,
  field_right = 23,
  field_single_value = 24,
  field_value = 25,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attribute] = "attribute",
  [field_close_angle] = "close_angle",
  [field_close_paren] = "close_paren",
  [field_comma] = "comma",
  [field_constant_value] = "constant_value",
  [field_dot] = "dot",
  [field_func_name] = "func_name",
  [field_key] = "key",
  [field_key_attribute] = "key_attribute",
  [field_left] = "left",
  [field_may] = "may",
  [field_must] = "must",
  [field_number] = "number",
  [field_object] = "object",
  [field_open_angle] = "open_angle",
  [field_open_paren] = "open_paren",
  [field_operation] = "operation",
  [field_operation_name] = "operation_name",
  [field_operator] = "operator",
  [field_or] = "or",
  [field_possibility] = "possibility",
  [field_range_value] = "range_value",
  [field_right] = "right",
  [field_single_value] = "single_value",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 3},
  [6] = {.index = 7, .length = 3},
  [7] = {.index = 10, .length = 1},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 1},
  [10] = {.index = 13, .length = 3},
  [11] = {.index = 16, .length = 4},
  [12] = {.index = 20, .length = 1},
  [13] = {.index = 21, .length = 1},
  [14] = {.index = 22, .length = 3},
  [15] = {.index = 25, .length = 3},
  [16] = {.index = 28, .length = 6},
  [17] = {.index = 34, .length = 6},
  [18] = {.index = 40, .length = 6},
  [19] = {.index = 46, .length = 2},
  [20] = {.index = 48, .length = 6},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_operation, 0},
  [1] =
    {field_key, 0},
  [2] =
    {field_key_attribute, 0},
  [3] =
    {field_constant_value, 0},
  [4] =
    {field_close_angle, 2},
    {field_number, 1},
    {field_open_angle, 0},
  [7] =
    {field_left, 0},
    {field_operation_name, 1},
    {field_right, 2},
  [10] =
    {field_value, 0},
  [11] =
    {field_single_value, 0},
  [12] =
    {field_range_value, 0},
  [13] =
    {field_attribute, 2},
    {field_dot, 1},
    {field_key, 0},
  [16] =
    {field_close_paren, 3},
    {field_key, 2},
    {field_open_paren, 1},
    {field_operation_name, 0},
  [20] =
    {field_may, 0},
  [21] =
    {field_must, 0},
  [22] =
    {field_or, 1},
    {field_value, 0},
    {field_value, 2},
  [25] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [28] =
    {field_close_paren, 5},
    {field_comma, 3},
    {field_object, 2},
    {field_open_paren, 1},
    {field_operation_name, 0},
    {field_possibility, 4},
  [34] =
    {field_close_paren, 5},
    {field_comma, 3},
    {field_object, 2},
    {field_open_paren, 1},
    {field_operation_name, 0},
    {field_range_value, 4},
  [40] =
    {field_close_paren, 5},
    {field_comma, 3},
    {field_left, 2},
    {field_open_paren, 1},
    {field_operation_name, 0},
    {field_right, 4},
  [46] =
    {field_left, 1},
    {field_right, 3},
  [48] =
    {field_close_paren, 5},
    {field_comma, 3},
    {field_func_name, 0},
    {field_left, 2},
    {field_open_paren, 1},
    {field_right, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(65);
      ADVANCE_MAP(
        '(', 70,
        ')', 72,
        '*', 123,
        '+', 121,
        ',', 71,
        '-', 122,
        '.', 94,
        '/', 124,
        '0', 83,
        '1', 84,
        '2', 85,
        '3', 86,
        '4', 87,
        '5', 88,
        '6', 89,
        '7', 90,
        '8', 91,
        '9', 92,
        '<', 81,
        '=', 68,
        '>', 93,
        'A', 115,
        'B', 116,
        'C', 117,
        'D', 118,
        'E', 119,
        'F', 120,
        'M', 4,
        'N', 14,
        'U', 11,
        '[', 125,
        ']', 126,
        'a', 107,
        'b', 108,
        'c', 109,
        'd', 110,
        'e', 111,
        'f', 113,
        'm', 17,
        'o', 60,
        's', 35,
        '{', 66,
        '|', 64,
        '}', 67,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        ')', 72,
        '*', 123,
        '+', 121,
        ',', 71,
        '-', 122,
        '.', 94,
        '/', 124,
        '0', 83,
        '1', 84,
        '2', 85,
        '3', 86,
        '4', 87,
        '5', 88,
        '6', 89,
        '7', 90,
        '8', 91,
        '9', 92,
        '<', 81,
        '=', 68,
        'A', 115,
        'B', 116,
        'C', 117,
        'D', 118,
        'E', 119,
        'F', 120,
        'M', 4,
        'N', 14,
        'U', 11,
        '[', 125,
        ']', 126,
        'a', 107,
        'b', 108,
        'c', 109,
        'd', 110,
        'e', 112,
        'f', 114,
        'm', 18,
        'o', 60,
        's', 61,
        '|', 64,
        '}', 67,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '-', 3,
        '0', 83,
        '1', 84,
        '2', 85,
        '3', 86,
        '4', 87,
        '5', 88,
        '6', 89,
        '7', 90,
        '8', 91,
        '9', 92,
        'b', 27,
        'e', 44,
        'f', 33,
        's', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '1') ADVANCE(82);
      END_STATE();
    case 4:
      if (lookahead == 'A') ADVANCE(16);
      if (lookahead == 'I') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'D') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == 'E') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'F') ADVANCE(103);
      END_STATE();
    case 8:
      if (lookahead == 'F') ADVANCE(105);
      END_STATE();
    case 9:
      if (lookahead == 'L') ADVANCE(104);
      END_STATE();
    case 10:
      if (lookahead == 'L') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'N') ADVANCE(5);
      END_STATE();
    case 12:
      if (lookahead == 'N') ADVANCE(102);
      END_STATE();
    case 13:
      if (lookahead == 'O') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'P') ADVANCE(13);
      if (lookahead == 'U') ADVANCE(10);
      END_STATE();
    case 15:
      if (lookahead == 'S') ADVANCE(106);
      END_STATE();
    case 16:
      if (lookahead == 'X') ADVANCE(101);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(41);
      if (lookahead == 'i') ADVANCE(45);
      if (lookahead == 'u') ADVANCE(57);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(40);
      if (lookahead == 'i') ADVANCE(45);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(69);
      END_STATE();
    case 22:
      if (lookahead == 'd') ADVANCE(98);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(99);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(95);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 31:
      if (lookahead == 'f') ADVANCE(42);
      END_STATE();
    case 32:
      if (lookahead == 'g') ADVANCE(37);
      END_STATE();
    case 33:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(63);
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 35:
      if (lookahead == 'i') ADVANCE(63);
      if (lookahead == 't') ADVANCE(56);
      if (lookahead == 'w') ADVANCE(19);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 39:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(38);
      if (lookahead == 'x') ADVANCE(80);
      END_STATE();
    case 41:
      if (lookahead == 'l') ADVANCE(38);
      if (lookahead == 'x') ADVANCE(80);
      if (lookahead == 'y') ADVANCE(77);
      END_STATE();
    case 42:
      if (lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 43:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 44:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 45:
      if (lookahead == 'n') ADVANCE(79);
      END_STATE();
    case 46:
      if (lookahead == 'n') ADVANCE(96);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(75);
      END_STATE();
    case 48:
      if (lookahead == 'n') ADVANCE(97);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 50:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 51:
      if (lookahead == 'o') ADVANCE(62);
      END_STATE();
    case 52:
      if (lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 53:
      if (lookahead == 'p') ADVANCE(76);
      END_STATE();
    case 54:
      if (lookahead == 'p') ADVANCE(20);
      END_STATE();
    case 55:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 56:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 57:
      if (lookahead == 's') ADVANCE(59);
      END_STATE();
    case 58:
      if (lookahead == 's') ADVANCE(36);
      END_STATE();
    case 59:
      if (lookahead == 't') ADVANCE(78);
      END_STATE();
    case 60:
      if (lookahead == 'v') ADVANCE(28);
      END_STATE();
    case 61:
      if (lookahead == 'w') ADVANCE(19);
      END_STATE();
    case 62:
      if (lookahead == 'w') ADVANCE(74);
      END_STATE();
    case 63:
      if (lookahead == 'z') ADVANCE(26);
      END_STATE();
    case 64:
      if (lookahead == '|') ADVANCE(100);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_malloc);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_free);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_overflow);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_expansion);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_swap);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_may);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_must);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_min);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_max);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_DASH1);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_0);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_1);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_2);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_3);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_4);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_5);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_6);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_7);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_8);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_9);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_size);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_strlen);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_begin);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_field);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_MAX);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_MIN);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_EOF);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_NULL);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_UNDEF);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_NPOS);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_a);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_b);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_c);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_d);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_e);
      if (lookahead == 'n') ADVANCE(22);
      if (lookahead == 'x') ADVANCE(54);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_e);
      if (lookahead == 'x') ADVANCE(54);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_f);
      if (lookahead == 'i') ADVANCE(24);
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_f);
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_A);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_B);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_C);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_D);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_E);
      if (lookahead == 'O') ADVANCE(7);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_F);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_malloc] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_free] = ACTIONS(1),
    [anon_sym_overflow] = ACTIONS(1),
    [anon_sym_expansion] = ACTIONS(1),
    [anon_sym_swap] = ACTIONS(1),
    [anon_sym_may] = ACTIONS(1),
    [anon_sym_must] = ACTIONS(1),
    [anon_sym_min] = ACTIONS(1),
    [anon_sym_max] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [anon_sym_1] = ACTIONS(1),
    [anon_sym_2] = ACTIONS(1),
    [anon_sym_3] = ACTIONS(1),
    [anon_sym_4] = ACTIONS(1),
    [anon_sym_5] = ACTIONS(1),
    [anon_sym_6] = ACTIONS(1),
    [anon_sym_7] = ACTIONS(1),
    [anon_sym_8] = ACTIONS(1),
    [anon_sym_9] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_size] = ACTIONS(1),
    [anon_sym_strlen] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_field] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_MAX] = ACTIONS(1),
    [anon_sym_MIN] = ACTIONS(1),
    [anon_sym_EOF] = ACTIONS(1),
    [anon_sym_NULL] = ACTIONS(1),
    [anon_sym_UNDEF] = ACTIONS(1),
    [anon_sym_NPOS] = ACTIONS(1),
    [anon_sym_a] = ACTIONS(1),
    [anon_sym_b] = ACTIONS(1),
    [anon_sym_c] = ACTIONS(1),
    [anon_sym_d] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_f] = ACTIONS(1),
    [anon_sym_A] = ACTIONS(1),
    [anon_sym_B] = ACTIONS(1),
    [anon_sym_C] = ACTIONS(1),
    [anon_sym_D] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [anon_sym_F] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(51),
    [sym_memory_summary] = STATE(71),
    [anon_sym_LBRACE] = ACTIONS(3),
  },
  [2] = {
    [sym_side_effects] = STATE(73),
    [sym_memory_side_effect] = STATE(4),
    [sym_assign] = STATE(31),
    [sym_malloc] = STATE(31),
    [sym_free] = STATE(31),
    [sym_overflow] = STATE(31),
    [sym_expansion] = STATE(31),
    [sym_swap] = STATE(31),
    [sym_object] = STATE(68),
    [sym_key] = STATE(5),
    [sym_key_attribute] = STATE(11),
    [sym_constant_value] = STATE(9),
    [sym_number] = STATE(7),
    [sym_alpha] = STATE(7),
    [aux_sym_side_effects_repeat1] = STATE(4),
    [anon_sym_RBRACE] = ACTIONS(5),
    [anon_sym_malloc] = ACTIONS(7),
    [anon_sym_free] = ACTIONS(9),
    [anon_sym_overflow] = ACTIONS(11),
    [anon_sym_expansion] = ACTIONS(13),
    [anon_sym_swap] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_0] = ACTIONS(19),
    [anon_sym_1] = ACTIONS(19),
    [anon_sym_2] = ACTIONS(19),
    [anon_sym_3] = ACTIONS(19),
    [anon_sym_4] = ACTIONS(19),
    [anon_sym_5] = ACTIONS(19),
    [anon_sym_6] = ACTIONS(19),
    [anon_sym_7] = ACTIONS(19),
    [anon_sym_8] = ACTIONS(19),
    [anon_sym_9] = ACTIONS(19),
    [anon_sym_MAX] = ACTIONS(21),
    [anon_sym_MIN] = ACTIONS(21),
    [anon_sym_EOF] = ACTIONS(21),
    [anon_sym_NULL] = ACTIONS(21),
    [anon_sym_UNDEF] = ACTIONS(21),
    [anon_sym_NPOS] = ACTIONS(21),
    [anon_sym_a] = ACTIONS(23),
    [anon_sym_b] = ACTIONS(23),
    [anon_sym_c] = ACTIONS(23),
    [anon_sym_d] = ACTIONS(23),
    [anon_sym_e] = ACTIONS(25),
    [anon_sym_f] = ACTIONS(25),
    [anon_sym_A] = ACTIONS(23),
    [anon_sym_B] = ACTIONS(23),
    [anon_sym_C] = ACTIONS(23),
    [anon_sym_D] = ACTIONS(23),
    [anon_sym_E] = ACTIONS(25),
    [anon_sym_F] = ACTIONS(23),
  },
  [3] = {
    [sym_memory_side_effect] = STATE(3),
    [sym_assign] = STATE(31),
    [sym_malloc] = STATE(31),
    [sym_free] = STATE(31),
    [sym_overflow] = STATE(31),
    [sym_expansion] = STATE(31),
    [sym_swap] = STATE(31),
    [sym_object] = STATE(68),
    [sym_key] = STATE(5),
    [sym_key_attribute] = STATE(11),
    [sym_constant_value] = STATE(9),
    [sym_number] = STATE(7),
    [sym_alpha] = STATE(7),
    [aux_sym_side_effects_repeat1] = STATE(3),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_malloc] = ACTIONS(29),
    [anon_sym_free] = ACTIONS(32),
    [anon_sym_overflow] = ACTIONS(35),
    [anon_sym_expansion] = ACTIONS(38),
    [anon_sym_swap] = ACTIONS(41),
    [anon_sym_LT] = ACTIONS(44),
    [anon_sym_0] = ACTIONS(47),
    [anon_sym_1] = ACTIONS(47),
    [anon_sym_2] = ACTIONS(47),
    [anon_sym_3] = ACTIONS(47),
    [anon_sym_4] = ACTIONS(47),
    [anon_sym_5] = ACTIONS(47),
    [anon_sym_6] = ACTIONS(47),
    [anon_sym_7] = ACTIONS(47),
    [anon_sym_8] = ACTIONS(47),
    [anon_sym_9] = ACTIONS(47),
    [anon_sym_MAX] = ACTIONS(50),
    [anon_sym_MIN] = ACTIONS(50),
    [anon_sym_EOF] = ACTIONS(50),
    [anon_sym_NULL] = ACTIONS(50),
    [anon_sym_UNDEF] = ACTIONS(50),
    [anon_sym_NPOS] = ACTIONS(50),
    [anon_sym_a] = ACTIONS(53),
    [anon_sym_b] = ACTIONS(53),
    [anon_sym_c] = ACTIONS(53),
    [anon_sym_d] = ACTIONS(53),
    [anon_sym_e] = ACTIONS(56),
    [anon_sym_f] = ACTIONS(56),
    [anon_sym_A] = ACTIONS(53),
    [anon_sym_B] = ACTIONS(53),
    [anon_sym_C] = ACTIONS(53),
    [anon_sym_D] = ACTIONS(53),
    [anon_sym_E] = ACTIONS(56),
    [anon_sym_F] = ACTIONS(53),
  },
  [4] = {
    [sym_memory_side_effect] = STATE(3),
    [sym_assign] = STATE(31),
    [sym_malloc] = STATE(31),
    [sym_free] = STATE(31),
    [sym_overflow] = STATE(31),
    [sym_expansion] = STATE(31),
    [sym_swap] = STATE(31),
    [sym_object] = STATE(68),
    [sym_key] = STATE(5),
    [sym_key_attribute] = STATE(11),
    [sym_constant_value] = STATE(9),
    [sym_number] = STATE(7),
    [sym_alpha] = STATE(7),
    [aux_sym_side_effects_repeat1] = STATE(3),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_malloc] = ACTIONS(7),
    [anon_sym_free] = ACTIONS(9),
    [anon_sym_overflow] = ACTIONS(11),
    [anon_sym_expansion] = ACTIONS(13),
    [anon_sym_swap] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_0] = ACTIONS(19),
    [anon_sym_1] = ACTIONS(19),
    [anon_sym_2] = ACTIONS(19),
    [anon_sym_3] = ACTIONS(19),
    [anon_sym_4] = ACTIONS(19),
    [anon_sym_5] = ACTIONS(19),
    [anon_sym_6] = ACTIONS(19),
    [anon_sym_7] = ACTIONS(19),
    [anon_sym_8] = ACTIONS(19),
    [anon_sym_9] = ACTIONS(19),
    [anon_sym_MAX] = ACTIONS(21),
    [anon_sym_MIN] = ACTIONS(21),
    [anon_sym_EOF] = ACTIONS(21),
    [anon_sym_NULL] = ACTIONS(21),
    [anon_sym_UNDEF] = ACTIONS(21),
    [anon_sym_NPOS] = ACTIONS(21),
    [anon_sym_a] = ACTIONS(23),
    [anon_sym_b] = ACTIONS(23),
    [anon_sym_c] = ACTIONS(23),
    [anon_sym_d] = ACTIONS(23),
    [anon_sym_e] = ACTIONS(25),
    [anon_sym_f] = ACTIONS(25),
    [anon_sym_A] = ACTIONS(23),
    [anon_sym_B] = ACTIONS(23),
    [anon_sym_C] = ACTIONS(23),
    [anon_sym_D] = ACTIONS(23),
    [anon_sym_E] = ACTIONS(25),
    [anon_sym_F] = ACTIONS(23),
  },
  [5] = {
    [anon_sym_RBRACE] = ACTIONS(61),
    [anon_sym_EQ] = ACTIONS(61),
    [anon_sym_malloc] = ACTIONS(61),
    [anon_sym_COMMA] = ACTIONS(61),
    [anon_sym_RPAREN] = ACTIONS(61),
    [anon_sym_free] = ACTIONS(61),
    [anon_sym_overflow] = ACTIONS(61),
    [anon_sym_expansion] = ACTIONS(61),
    [anon_sym_swap] = ACTIONS(61),
    [anon_sym_LT] = ACTIONS(61),
    [anon_sym_0] = ACTIONS(61),
    [anon_sym_1] = ACTIONS(61),
    [anon_sym_2] = ACTIONS(61),
    [anon_sym_3] = ACTIONS(61),
    [anon_sym_4] = ACTIONS(61),
    [anon_sym_5] = ACTIONS(61),
    [anon_sym_6] = ACTIONS(61),
    [anon_sym_7] = ACTIONS(61),
    [anon_sym_8] = ACTIONS(61),
    [anon_sym_9] = ACTIONS(61),
    [anon_sym_DOT] = ACTIONS(63),
    [anon_sym_PIPE_PIPE] = ACTIONS(61),
    [anon_sym_MAX] = ACTIONS(61),
    [anon_sym_MIN] = ACTIONS(61),
    [anon_sym_EOF] = ACTIONS(61),
    [anon_sym_NULL] = ACTIONS(61),
    [anon_sym_UNDEF] = ACTIONS(61),
    [anon_sym_NPOS] = ACTIONS(61),
    [anon_sym_a] = ACTIONS(61),
    [anon_sym_b] = ACTIONS(61),
    [anon_sym_c] = ACTIONS(61),
    [anon_sym_d] = ACTIONS(61),
    [anon_sym_e] = ACTIONS(65),
    [anon_sym_f] = ACTIONS(65),
    [anon_sym_A] = ACTIONS(61),
    [anon_sym_B] = ACTIONS(61),
    [anon_sym_C] = ACTIONS(61),
    [anon_sym_D] = ACTIONS(61),
    [anon_sym_E] = ACTIONS(65),
    [anon_sym_F] = ACTIONS(61),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_STAR] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(61),
    [anon_sym_RBRACK] = ACTIONS(61),
  },
  [6] = {
    [anon_sym_RBRACE] = ACTIONS(67),
    [anon_sym_EQ] = ACTIONS(67),
    [anon_sym_malloc] = ACTIONS(67),
    [anon_sym_COMMA] = ACTIONS(67),
    [anon_sym_RPAREN] = ACTIONS(67),
    [anon_sym_free] = ACTIONS(67),
    [anon_sym_overflow] = ACTIONS(67),
    [anon_sym_expansion] = ACTIONS(67),
    [anon_sym_swap] = ACTIONS(67),
    [anon_sym_LT] = ACTIONS(67),
    [anon_sym_0] = ACTIONS(67),
    [anon_sym_1] = ACTIONS(67),
    [anon_sym_2] = ACTIONS(67),
    [anon_sym_3] = ACTIONS(67),
    [anon_sym_4] = ACTIONS(67),
    [anon_sym_5] = ACTIONS(67),
    [anon_sym_6] = ACTIONS(67),
    [anon_sym_7] = ACTIONS(67),
    [anon_sym_8] = ACTIONS(67),
    [anon_sym_9] = ACTIONS(67),
    [anon_sym_DOT] = ACTIONS(67),
    [anon_sym_PIPE_PIPE] = ACTIONS(67),
    [anon_sym_MAX] = ACTIONS(67),
    [anon_sym_MIN] = ACTIONS(67),
    [anon_sym_EOF] = ACTIONS(67),
    [anon_sym_NULL] = ACTIONS(67),
    [anon_sym_UNDEF] = ACTIONS(67),
    [anon_sym_NPOS] = ACTIONS(67),
    [anon_sym_a] = ACTIONS(67),
    [anon_sym_b] = ACTIONS(67),
    [anon_sym_c] = ACTIONS(67),
    [anon_sym_d] = ACTIONS(67),
    [anon_sym_e] = ACTIONS(69),
    [anon_sym_f] = ACTIONS(69),
    [anon_sym_A] = ACTIONS(67),
    [anon_sym_B] = ACTIONS(67),
    [anon_sym_C] = ACTIONS(67),
    [anon_sym_D] = ACTIONS(67),
    [anon_sym_E] = ACTIONS(69),
    [anon_sym_F] = ACTIONS(67),
    [anon_sym_PLUS] = ACTIONS(67),
    [anon_sym_DASH] = ACTIONS(67),
    [anon_sym_STAR] = ACTIONS(67),
    [anon_sym_SLASH] = ACTIONS(67),
    [anon_sym_RBRACK] = ACTIONS(67),
  },
  [7] = {
    [anon_sym_RBRACE] = ACTIONS(71),
    [anon_sym_EQ] = ACTIONS(71),
    [anon_sym_malloc] = ACTIONS(71),
    [anon_sym_COMMA] = ACTIONS(71),
    [anon_sym_RPAREN] = ACTIONS(71),
    [anon_sym_free] = ACTIONS(71),
    [anon_sym_overflow] = ACTIONS(71),
    [anon_sym_expansion] = ACTIONS(71),
    [anon_sym_swap] = ACTIONS(71),
    [anon_sym_LT] = ACTIONS(71),
    [anon_sym_0] = ACTIONS(71),
    [anon_sym_1] = ACTIONS(71),
    [anon_sym_2] = ACTIONS(71),
    [anon_sym_3] = ACTIONS(71),
    [anon_sym_4] = ACTIONS(71),
    [anon_sym_5] = ACTIONS(71),
    [anon_sym_6] = ACTIONS(71),
    [anon_sym_7] = ACTIONS(71),
    [anon_sym_8] = ACTIONS(71),
    [anon_sym_9] = ACTIONS(71),
    [anon_sym_PIPE_PIPE] = ACTIONS(71),
    [anon_sym_MAX] = ACTIONS(71),
    [anon_sym_MIN] = ACTIONS(71),
    [anon_sym_EOF] = ACTIONS(71),
    [anon_sym_NULL] = ACTIONS(71),
    [anon_sym_UNDEF] = ACTIONS(71),
    [anon_sym_NPOS] = ACTIONS(71),
    [anon_sym_a] = ACTIONS(71),
    [anon_sym_b] = ACTIONS(71),
    [anon_sym_c] = ACTIONS(71),
    [anon_sym_d] = ACTIONS(71),
    [anon_sym_e] = ACTIONS(73),
    [anon_sym_f] = ACTIONS(73),
    [anon_sym_A] = ACTIONS(71),
    [anon_sym_B] = ACTIONS(71),
    [anon_sym_C] = ACTIONS(71),
    [anon_sym_D] = ACTIONS(71),
    [anon_sym_E] = ACTIONS(73),
    [anon_sym_F] = ACTIONS(71),
    [anon_sym_PLUS] = ACTIONS(71),
    [anon_sym_DASH] = ACTIONS(71),
    [anon_sym_STAR] = ACTIONS(71),
    [anon_sym_SLASH] = ACTIONS(71),
    [anon_sym_RBRACK] = ACTIONS(71),
  },
  [8] = {
    [anon_sym_RBRACE] = ACTIONS(75),
    [anon_sym_EQ] = ACTIONS(75),
    [anon_sym_malloc] = ACTIONS(75),
    [anon_sym_COMMA] = ACTIONS(75),
    [anon_sym_RPAREN] = ACTIONS(75),
    [anon_sym_free] = ACTIONS(75),
    [anon_sym_overflow] = ACTIONS(75),
    [anon_sym_expansion] = ACTIONS(75),
    [anon_sym_swap] = ACTIONS(75),
    [anon_sym_LT] = ACTIONS(75),
    [anon_sym_0] = ACTIONS(75),
    [anon_sym_1] = ACTIONS(75),
    [anon_sym_2] = ACTIONS(75),
    [anon_sym_3] = ACTIONS(75),
    [anon_sym_4] = ACTIONS(75),
    [anon_sym_5] = ACTIONS(75),
    [anon_sym_6] = ACTIONS(75),
    [anon_sym_7] = ACTIONS(75),
    [anon_sym_8] = ACTIONS(75),
    [anon_sym_9] = ACTIONS(75),
    [anon_sym_PIPE_PIPE] = ACTIONS(75),
    [anon_sym_MAX] = ACTIONS(75),
    [anon_sym_MIN] = ACTIONS(75),
    [anon_sym_EOF] = ACTIONS(75),
    [anon_sym_NULL] = ACTIONS(75),
    [anon_sym_UNDEF] = ACTIONS(75),
    [anon_sym_NPOS] = ACTIONS(75),
    [anon_sym_a] = ACTIONS(75),
    [anon_sym_b] = ACTIONS(75),
    [anon_sym_c] = ACTIONS(75),
    [anon_sym_d] = ACTIONS(75),
    [anon_sym_e] = ACTIONS(77),
    [anon_sym_f] = ACTIONS(77),
    [anon_sym_A] = ACTIONS(75),
    [anon_sym_B] = ACTIONS(75),
    [anon_sym_C] = ACTIONS(75),
    [anon_sym_D] = ACTIONS(75),
    [anon_sym_E] = ACTIONS(77),
    [anon_sym_F] = ACTIONS(75),
    [anon_sym_PLUS] = ACTIONS(75),
    [anon_sym_DASH] = ACTIONS(75),
    [anon_sym_STAR] = ACTIONS(75),
    [anon_sym_SLASH] = ACTIONS(75),
    [anon_sym_RBRACK] = ACTIONS(75),
  },
  [9] = {
    [anon_sym_RBRACE] = ACTIONS(79),
    [anon_sym_EQ] = ACTIONS(79),
    [anon_sym_malloc] = ACTIONS(79),
    [anon_sym_COMMA] = ACTIONS(79),
    [anon_sym_RPAREN] = ACTIONS(79),
    [anon_sym_free] = ACTIONS(79),
    [anon_sym_overflow] = ACTIONS(79),
    [anon_sym_expansion] = ACTIONS(79),
    [anon_sym_swap] = ACTIONS(79),
    [anon_sym_LT] = ACTIONS(79),
    [anon_sym_0] = ACTIONS(79),
    [anon_sym_1] = ACTIONS(79),
    [anon_sym_2] = ACTIONS(79),
    [anon_sym_3] = ACTIONS(79),
    [anon_sym_4] = ACTIONS(79),
    [anon_sym_5] = ACTIONS(79),
    [anon_sym_6] = ACTIONS(79),
    [anon_sym_7] = ACTIONS(79),
    [anon_sym_8] = ACTIONS(79),
    [anon_sym_9] = ACTIONS(79),
    [anon_sym_PIPE_PIPE] = ACTIONS(79),
    [anon_sym_MAX] = ACTIONS(79),
    [anon_sym_MIN] = ACTIONS(79),
    [anon_sym_EOF] = ACTIONS(79),
    [anon_sym_NULL] = ACTIONS(79),
    [anon_sym_UNDEF] = ACTIONS(79),
    [anon_sym_NPOS] = ACTIONS(79),
    [anon_sym_a] = ACTIONS(79),
    [anon_sym_b] = ACTIONS(79),
    [anon_sym_c] = ACTIONS(79),
    [anon_sym_d] = ACTIONS(79),
    [anon_sym_e] = ACTIONS(81),
    [anon_sym_f] = ACTIONS(81),
    [anon_sym_A] = ACTIONS(79),
    [anon_sym_B] = ACTIONS(79),
    [anon_sym_C] = ACTIONS(79),
    [anon_sym_D] = ACTIONS(79),
    [anon_sym_E] = ACTIONS(81),
    [anon_sym_F] = ACTIONS(79),
    [anon_sym_PLUS] = ACTIONS(79),
    [anon_sym_DASH] = ACTIONS(79),
    [anon_sym_STAR] = ACTIONS(79),
    [anon_sym_SLASH] = ACTIONS(79),
    [anon_sym_RBRACK] = ACTIONS(79),
  },
  [10] = {
    [anon_sym_RBRACE] = ACTIONS(83),
    [anon_sym_EQ] = ACTIONS(83),
    [anon_sym_malloc] = ACTIONS(83),
    [anon_sym_COMMA] = ACTIONS(83),
    [anon_sym_RPAREN] = ACTIONS(83),
    [anon_sym_free] = ACTIONS(83),
    [anon_sym_overflow] = ACTIONS(83),
    [anon_sym_expansion] = ACTIONS(83),
    [anon_sym_swap] = ACTIONS(83),
    [anon_sym_LT] = ACTIONS(83),
    [anon_sym_0] = ACTIONS(83),
    [anon_sym_1] = ACTIONS(83),
    [anon_sym_2] = ACTIONS(83),
    [anon_sym_3] = ACTIONS(83),
    [anon_sym_4] = ACTIONS(83),
    [anon_sym_5] = ACTIONS(83),
    [anon_sym_6] = ACTIONS(83),
    [anon_sym_7] = ACTIONS(83),
    [anon_sym_8] = ACTIONS(83),
    [anon_sym_9] = ACTIONS(83),
    [anon_sym_PIPE_PIPE] = ACTIONS(83),
    [anon_sym_MAX] = ACTIONS(83),
    [anon_sym_MIN] = ACTIONS(83),
    [anon_sym_EOF] = ACTIONS(83),
    [anon_sym_NULL] = ACTIONS(83),
    [anon_sym_UNDEF] = ACTIONS(83),
    [anon_sym_NPOS] = ACTIONS(83),
    [anon_sym_a] = ACTIONS(83),
    [anon_sym_b] = ACTIONS(83),
    [anon_sym_c] = ACTIONS(83),
    [anon_sym_d] = ACTIONS(83),
    [anon_sym_e] = ACTIONS(85),
    [anon_sym_f] = ACTIONS(85),
    [anon_sym_A] = ACTIONS(83),
    [anon_sym_B] = ACTIONS(83),
    [anon_sym_C] = ACTIONS(83),
    [anon_sym_D] = ACTIONS(83),
    [anon_sym_E] = ACTIONS(85),
    [anon_sym_F] = ACTIONS(83),
    [anon_sym_PLUS] = ACTIONS(83),
    [anon_sym_DASH] = ACTIONS(83),
    [anon_sym_STAR] = ACTIONS(83),
    [anon_sym_SLASH] = ACTIONS(83),
    [anon_sym_RBRACK] = ACTIONS(83),
  },
  [11] = {
    [anon_sym_RBRACE] = ACTIONS(87),
    [anon_sym_EQ] = ACTIONS(87),
    [anon_sym_malloc] = ACTIONS(87),
    [anon_sym_COMMA] = ACTIONS(87),
    [anon_sym_RPAREN] = ACTIONS(87),
    [anon_sym_free] = ACTIONS(87),
    [anon_sym_overflow] = ACTIONS(87),
    [anon_sym_expansion] = ACTIONS(87),
    [anon_sym_swap] = ACTIONS(87),
    [anon_sym_LT] = ACTIONS(87),
    [anon_sym_0] = ACTIONS(87),
    [anon_sym_1] = ACTIONS(87),
    [anon_sym_2] = ACTIONS(87),
    [anon_sym_3] = ACTIONS(87),
    [anon_sym_4] = ACTIONS(87),
    [anon_sym_5] = ACTIONS(87),
    [anon_sym_6] = ACTIONS(87),
    [anon_sym_7] = ACTIONS(87),
    [anon_sym_8] = ACTIONS(87),
    [anon_sym_9] = ACTIONS(87),
    [anon_sym_PIPE_PIPE] = ACTIONS(87),
    [anon_sym_MAX] = ACTIONS(87),
    [anon_sym_MIN] = ACTIONS(87),
    [anon_sym_EOF] = ACTIONS(87),
    [anon_sym_NULL] = ACTIONS(87),
    [anon_sym_UNDEF] = ACTIONS(87),
    [anon_sym_NPOS] = ACTIONS(87),
    [anon_sym_a] = ACTIONS(87),
    [anon_sym_b] = ACTIONS(87),
    [anon_sym_c] = ACTIONS(87),
    [anon_sym_d] = ACTIONS(87),
    [anon_sym_e] = ACTIONS(89),
    [anon_sym_f] = ACTIONS(89),
    [anon_sym_A] = ACTIONS(87),
    [anon_sym_B] = ACTIONS(87),
    [anon_sym_C] = ACTIONS(87),
    [anon_sym_D] = ACTIONS(87),
    [anon_sym_E] = ACTIONS(89),
    [anon_sym_F] = ACTIONS(87),
    [anon_sym_PLUS] = ACTIONS(87),
    [anon_sym_DASH] = ACTIONS(87),
    [anon_sym_STAR] = ACTIONS(87),
    [anon_sym_SLASH] = ACTIONS(87),
    [anon_sym_RBRACK] = ACTIONS(87),
  },
  [12] = {
    [anon_sym_RBRACE] = ACTIONS(91),
    [anon_sym_EQ] = ACTIONS(91),
    [anon_sym_malloc] = ACTIONS(91),
    [anon_sym_COMMA] = ACTIONS(91),
    [anon_sym_RPAREN] = ACTIONS(91),
    [anon_sym_free] = ACTIONS(91),
    [anon_sym_overflow] = ACTIONS(91),
    [anon_sym_expansion] = ACTIONS(91),
    [anon_sym_swap] = ACTIONS(91),
    [anon_sym_LT] = ACTIONS(91),
    [anon_sym_0] = ACTIONS(91),
    [anon_sym_1] = ACTIONS(91),
    [anon_sym_2] = ACTIONS(91),
    [anon_sym_3] = ACTIONS(91),
    [anon_sym_4] = ACTIONS(91),
    [anon_sym_5] = ACTIONS(91),
    [anon_sym_6] = ACTIONS(91),
    [anon_sym_7] = ACTIONS(91),
    [anon_sym_8] = ACTIONS(91),
    [anon_sym_9] = ACTIONS(91),
    [anon_sym_PIPE_PIPE] = ACTIONS(91),
    [anon_sym_MAX] = ACTIONS(91),
    [anon_sym_MIN] = ACTIONS(91),
    [anon_sym_EOF] = ACTIONS(91),
    [anon_sym_NULL] = ACTIONS(91),
    [anon_sym_UNDEF] = ACTIONS(91),
    [anon_sym_NPOS] = ACTIONS(91),
    [anon_sym_a] = ACTIONS(91),
    [anon_sym_b] = ACTIONS(91),
    [anon_sym_c] = ACTIONS(91),
    [anon_sym_d] = ACTIONS(91),
    [anon_sym_e] = ACTIONS(93),
    [anon_sym_f] = ACTIONS(93),
    [anon_sym_A] = ACTIONS(91),
    [anon_sym_B] = ACTIONS(91),
    [anon_sym_C] = ACTIONS(91),
    [anon_sym_D] = ACTIONS(91),
    [anon_sym_E] = ACTIONS(93),
    [anon_sym_F] = ACTIONS(91),
    [anon_sym_PLUS] = ACTIONS(91),
    [anon_sym_DASH] = ACTIONS(91),
    [anon_sym_STAR] = ACTIONS(91),
    [anon_sym_SLASH] = ACTIONS(91),
    [anon_sym_RBRACK] = ACTIONS(91),
  },
  [13] = {
    [anon_sym_RBRACE] = ACTIONS(95),
    [anon_sym_EQ] = ACTIONS(95),
    [anon_sym_malloc] = ACTIONS(95),
    [anon_sym_COMMA] = ACTIONS(95),
    [anon_sym_RPAREN] = ACTIONS(95),
    [anon_sym_free] = ACTIONS(95),
    [anon_sym_overflow] = ACTIONS(95),
    [anon_sym_expansion] = ACTIONS(95),
    [anon_sym_swap] = ACTIONS(95),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_0] = ACTIONS(95),
    [anon_sym_1] = ACTIONS(95),
    [anon_sym_2] = ACTIONS(95),
    [anon_sym_3] = ACTIONS(95),
    [anon_sym_4] = ACTIONS(95),
    [anon_sym_5] = ACTIONS(95),
    [anon_sym_6] = ACTIONS(95),
    [anon_sym_7] = ACTIONS(95),
    [anon_sym_8] = ACTIONS(95),
    [anon_sym_9] = ACTIONS(95),
    [anon_sym_PIPE_PIPE] = ACTIONS(95),
    [anon_sym_MAX] = ACTIONS(95),
    [anon_sym_MIN] = ACTIONS(95),
    [anon_sym_EOF] = ACTIONS(95),
    [anon_sym_NULL] = ACTIONS(95),
    [anon_sym_UNDEF] = ACTIONS(95),
    [anon_sym_NPOS] = ACTIONS(95),
    [anon_sym_a] = ACTIONS(95),
    [anon_sym_b] = ACTIONS(95),
    [anon_sym_c] = ACTIONS(95),
    [anon_sym_d] = ACTIONS(95),
    [anon_sym_e] = ACTIONS(97),
    [anon_sym_f] = ACTIONS(97),
    [anon_sym_A] = ACTIONS(95),
    [anon_sym_B] = ACTIONS(95),
    [anon_sym_C] = ACTIONS(95),
    [anon_sym_D] = ACTIONS(95),
    [anon_sym_E] = ACTIONS(97),
    [anon_sym_F] = ACTIONS(95),
    [anon_sym_PLUS] = ACTIONS(95),
    [anon_sym_DASH] = ACTIONS(95),
    [anon_sym_STAR] = ACTIONS(95),
    [anon_sym_SLASH] = ACTIONS(95),
    [anon_sym_RBRACK] = ACTIONS(95),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(101), 3,
      anon_sym_e,
      anon_sym_f,
      anon_sym_E,
    ACTIONS(99), 37,
      anon_sym_RBRACE,
      anon_sym_malloc,
      anon_sym_COMMA,
      anon_sym_free,
      anon_sym_overflow,
      anon_sym_expansion,
      anon_sym_swap,
      anon_sym_LT,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_PIPE_PIPE,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RBRACK,
  [49] = 2,
    ACTIONS(101), 3,
      anon_sym_e,
      anon_sym_f,
      anon_sym_E,
    ACTIONS(99), 39,
      anon_sym_RBRACE,
      anon_sym_malloc,
      anon_sym_COMMA,
      anon_sym_free,
      anon_sym_overflow,
      anon_sym_expansion,
      anon_sym_swap,
      anon_sym_LT,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_PIPE_PIPE,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
  [96] = 2,
    ACTIONS(107), 3,
      anon_sym_e,
      anon_sym_f,
      anon_sym_E,
    ACTIONS(105), 39,
      anon_sym_RBRACE,
      anon_sym_malloc,
      anon_sym_COMMA,
      anon_sym_free,
      anon_sym_overflow,
      anon_sym_expansion,
      anon_sym_swap,
      anon_sym_LT,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_PIPE_PIPE,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
  [143] = 15,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_E,
    ACTIONS(109), 1,
      anon_sym_LBRACK,
    STATE(5), 1,
      sym_key,
    STATE(9), 1,
      sym_constant_value,
    STATE(11), 1,
      sym_key_attribute,
    STATE(18), 1,
      sym_single_value,
    STATE(26), 1,
      sym_range_value,
    STATE(27), 1,
      sym_value,
    STATE(30), 1,
      sym_values,
    STATE(7), 2,
      sym_number,
      sym_alpha,
    STATE(16), 2,
      sym_object,
      sym_binary_expr,
    ACTIONS(21), 6,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
    ACTIONS(19), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
    ACTIONS(23), 11,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_f,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [215] = 4,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(113), 3,
      anon_sym_e,
      anon_sym_f,
      anon_sym_E,
    ACTIONS(111), 33,
      anon_sym_RBRACE,
      anon_sym_malloc,
      anon_sym_free,
      anon_sym_overflow,
      anon_sym_expansion,
      anon_sym_swap,
      anon_sym_LT,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_PIPE_PIPE,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [264] = 14,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_E,
    ACTIONS(109), 1,
      anon_sym_LBRACK,
    STATE(5), 1,
      sym_key,
    STATE(9), 1,
      sym_constant_value,
    STATE(11), 1,
      sym_key_attribute,
    STATE(18), 1,
      sym_single_value,
    STATE(26), 1,
      sym_range_value,
    STATE(36), 1,
      sym_value,
    STATE(7), 2,
      sym_number,
      sym_alpha,
    STATE(16), 2,
      sym_object,
      sym_binary_expr,
    ACTIONS(21), 6,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
    ACTIONS(19), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
    ACTIONS(23), 11,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_f,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [333] = 12,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_E,
    STATE(5), 1,
      sym_key,
    STATE(9), 1,
      sym_constant_value,
    STATE(11), 1,
      sym_key_attribute,
    STATE(57), 1,
      sym_overflow_arg,
    ACTIONS(117), 2,
      anon_sym_min,
      anon_sym_max,
    STATE(7), 2,
      sym_number,
      sym_alpha,
    STATE(56), 2,
      sym_object,
      sym_overflow_func,
    ACTIONS(21), 6,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
    ACTIONS(19), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
    ACTIONS(23), 11,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_f,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [397] = 11,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_E,
    STATE(5), 1,
      sym_key,
    STATE(9), 1,
      sym_constant_value,
    STATE(11), 1,
      sym_key_attribute,
    STATE(42), 1,
      sym_single_value,
    STATE(7), 2,
      sym_number,
      sym_alpha,
    STATE(16), 2,
      sym_object,
      sym_binary_expr,
    ACTIONS(21), 6,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
    ACTIONS(19), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
    ACTIONS(23), 11,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_f,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [457] = 11,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_E,
    STATE(5), 1,
      sym_key,
    STATE(9), 1,
      sym_constant_value,
    STATE(11), 1,
      sym_key_attribute,
    STATE(43), 1,
      sym_single_value,
    STATE(7), 2,
      sym_number,
      sym_alpha,
    STATE(16), 2,
      sym_object,
      sym_binary_expr,
    ACTIONS(21), 6,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
    ACTIONS(19), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
    ACTIONS(23), 11,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_f,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [517] = 11,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_E,
    STATE(5), 1,
      sym_key,
    STATE(9), 1,
      sym_constant_value,
    STATE(11), 1,
      sym_key_attribute,
    STATE(14), 1,
      sym_single_value,
    STATE(7), 2,
      sym_number,
      sym_alpha,
    STATE(16), 2,
      sym_object,
      sym_binary_expr,
    ACTIONS(21), 6,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
    ACTIONS(19), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
    ACTIONS(23), 11,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_f,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [577] = 11,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_E,
    STATE(5), 1,
      sym_key,
    STATE(9), 1,
      sym_constant_value,
    STATE(11), 1,
      sym_key_attribute,
    STATE(15), 1,
      sym_single_value,
    STATE(7), 2,
      sym_number,
      sym_alpha,
    STATE(16), 2,
      sym_object,
      sym_binary_expr,
    ACTIONS(21), 6,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
    ACTIONS(19), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
    ACTIONS(23), 11,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_f,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [637] = 2,
    ACTIONS(121), 3,
      anon_sym_e,
      anon_sym_f,
      anon_sym_E,
    ACTIONS(119), 34,
      anon_sym_RBRACE,
      anon_sym_malloc,
      anon_sym_RPAREN,
      anon_sym_free,
      anon_sym_overflow,
      anon_sym_expansion,
      anon_sym_swap,
      anon_sym_LT,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_PIPE_PIPE,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [679] = 2,
    ACTIONS(125), 3,
      anon_sym_e,
      anon_sym_f,
      anon_sym_E,
    ACTIONS(123), 33,
      anon_sym_RBRACE,
      anon_sym_malloc,
      anon_sym_free,
      anon_sym_overflow,
      anon_sym_expansion,
      anon_sym_swap,
      anon_sym_LT,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_PIPE_PIPE,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [720] = 3,
    ACTIONS(129), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(131), 3,
      anon_sym_e,
      anon_sym_f,
      anon_sym_E,
    ACTIONS(127), 32,
      anon_sym_RBRACE,
      anon_sym_malloc,
      anon_sym_free,
      anon_sym_overflow,
      anon_sym_expansion,
      anon_sym_swap,
      anon_sym_LT,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [763] = 2,
    ACTIONS(135), 3,
      anon_sym_e,
      anon_sym_f,
      anon_sym_E,
    ACTIONS(133), 32,
      anon_sym_RBRACE,
      anon_sym_malloc,
      anon_sym_free,
      anon_sym_overflow,
      anon_sym_expansion,
      anon_sym_swap,
      anon_sym_LT,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [803] = 2,
    ACTIONS(139), 3,
      anon_sym_e,
      anon_sym_f,
      anon_sym_E,
    ACTIONS(137), 32,
      anon_sym_RBRACE,
      anon_sym_malloc,
      anon_sym_free,
      anon_sym_overflow,
      anon_sym_expansion,
      anon_sym_swap,
      anon_sym_LT,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [843] = 2,
    ACTIONS(143), 3,
      anon_sym_e,
      anon_sym_f,
      anon_sym_E,
    ACTIONS(141), 32,
      anon_sym_RBRACE,
      anon_sym_malloc,
      anon_sym_free,
      anon_sym_overflow,
      anon_sym_expansion,
      anon_sym_swap,
      anon_sym_LT,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [883] = 2,
    ACTIONS(147), 3,
      anon_sym_e,
      anon_sym_f,
      anon_sym_E,
    ACTIONS(145), 32,
      anon_sym_RBRACE,
      anon_sym_malloc,
      anon_sym_free,
      anon_sym_overflow,
      anon_sym_expansion,
      anon_sym_swap,
      anon_sym_LT,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [923] = 10,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_E,
    STATE(5), 1,
      sym_key,
    STATE(9), 1,
      sym_constant_value,
    STATE(11), 1,
      sym_key_attribute,
    STATE(62), 1,
      sym_object,
    STATE(7), 2,
      sym_number,
      sym_alpha,
    ACTIONS(21), 6,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
    ACTIONS(19), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
    ACTIONS(23), 11,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_f,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [979] = 2,
    ACTIONS(151), 3,
      anon_sym_e,
      anon_sym_f,
      anon_sym_E,
    ACTIONS(149), 32,
      anon_sym_RBRACE,
      anon_sym_malloc,
      anon_sym_free,
      anon_sym_overflow,
      anon_sym_expansion,
      anon_sym_swap,
      anon_sym_LT,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [1019] = 10,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_E,
    STATE(5), 1,
      sym_key,
    STATE(9), 1,
      sym_constant_value,
    STATE(11), 1,
      sym_key_attribute,
    STATE(67), 1,
      sym_object,
    STATE(7), 2,
      sym_number,
      sym_alpha,
    ACTIONS(21), 6,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
    ACTIONS(19), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
    ACTIONS(23), 11,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_f,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [1075] = 10,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_E,
    STATE(5), 1,
      sym_key,
    STATE(9), 1,
      sym_constant_value,
    STATE(11), 1,
      sym_key_attribute,
    STATE(69), 1,
      sym_object,
    STATE(7), 2,
      sym_number,
      sym_alpha,
    ACTIONS(21), 6,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
    ACTIONS(19), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
    ACTIONS(23), 11,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_f,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [1131] = 2,
    ACTIONS(155), 3,
      anon_sym_e,
      anon_sym_f,
      anon_sym_E,
    ACTIONS(153), 32,
      anon_sym_RBRACE,
      anon_sym_malloc,
      anon_sym_free,
      anon_sym_overflow,
      anon_sym_expansion,
      anon_sym_swap,
      anon_sym_LT,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [1171] = 2,
    ACTIONS(159), 3,
      anon_sym_e,
      anon_sym_f,
      anon_sym_E,
    ACTIONS(157), 32,
      anon_sym_RBRACE,
      anon_sym_malloc,
      anon_sym_free,
      anon_sym_overflow,
      anon_sym_expansion,
      anon_sym_swap,
      anon_sym_LT,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [1211] = 10,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_E,
    STATE(5), 1,
      sym_key,
    STATE(9), 1,
      sym_constant_value,
    STATE(11), 1,
      sym_key_attribute,
    STATE(75), 1,
      sym_object,
    STATE(7), 2,
      sym_number,
      sym_alpha,
    ACTIONS(21), 6,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
    ACTIONS(19), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
    ACTIONS(23), 11,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_f,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [1267] = 2,
    ACTIONS(163), 3,
      anon_sym_e,
      anon_sym_f,
      anon_sym_E,
    ACTIONS(161), 32,
      anon_sym_RBRACE,
      anon_sym_malloc,
      anon_sym_free,
      anon_sym_overflow,
      anon_sym_expansion,
      anon_sym_swap,
      anon_sym_LT,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
      anon_sym_MAX,
      anon_sym_MIN,
      anon_sym_EOF,
      anon_sym_NULL,
      anon_sym_UNDEF,
      anon_sym_NPOS,
      anon_sym_a,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_A,
      anon_sym_B,
      anon_sym_C,
      anon_sym_D,
      anon_sym_F,
  [1307] = 1,
    ACTIONS(165), 11,
      anon_sym_DASH1,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1321] = 2,
    STATE(12), 1,
      sym_attribute,
    ACTIONS(167), 5,
      anon_sym_size,
      anon_sym_strlen,
      anon_sym_begin,
      anon_sym_end,
      anon_sym_field,
  [1332] = 3,
    ACTIONS(169), 1,
      anon_sym_COMMA,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1344] = 3,
    ACTIONS(171), 1,
      anon_sym_RBRACK,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1356] = 3,
    ACTIONS(173), 1,
      anon_sym_may,
    ACTIONS(175), 1,
      anon_sym_must,
    STATE(61), 1,
      sym_possibility,
  [1366] = 3,
    ACTIONS(173), 1,
      anon_sym_may,
    ACTIONS(175), 1,
      anon_sym_must,
    STATE(60), 1,
      sym_possibility,
  [1376] = 2,
    ACTIONS(109), 1,
      anon_sym_LBRACK,
    STATE(63), 1,
      sym_range_value,
  [1383] = 2,
    ACTIONS(17), 1,
      anon_sym_LT,
    STATE(66), 1,
      sym_key,
  [1390] = 2,
    ACTIONS(17), 1,
      anon_sym_LT,
    STATE(50), 1,
      sym_key,
  [1397] = 2,
    ACTIONS(17), 1,
      anon_sym_LT,
    STATE(64), 1,
      sym_key,
  [1404] = 1,
    ACTIONS(177), 1,
      anon_sym_COMMA,
  [1408] = 1,
    ACTIONS(179), 1,
      ts_builtin_sym_end,
  [1412] = 1,
    ACTIONS(181), 1,
      anon_sym_LPAREN,
  [1416] = 1,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
  [1420] = 1,
    ACTIONS(185), 1,
      anon_sym_LPAREN,
  [1424] = 1,
    ACTIONS(187), 1,
      anon_sym_LPAREN,
  [1428] = 1,
    ACTIONS(189), 1,
      anon_sym_COMMA,
  [1432] = 1,
    ACTIONS(191), 1,
      anon_sym_COMMA,
  [1436] = 1,
    ACTIONS(193), 1,
      anon_sym_RPAREN,
  [1440] = 1,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
  [1444] = 1,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
  [1448] = 1,
    ACTIONS(199), 1,
      anon_sym_RPAREN,
  [1452] = 1,
    ACTIONS(201), 1,
      anon_sym_COMMA,
  [1456] = 1,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
  [1460] = 1,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
  [1464] = 1,
    ACTIONS(207), 1,
      anon_sym_LPAREN,
  [1468] = 1,
    ACTIONS(209), 1,
      anon_sym_RPAREN,
  [1472] = 1,
    ACTIONS(211), 1,
      anon_sym_COMMA,
  [1476] = 1,
    ACTIONS(213), 1,
      anon_sym_EQ,
  [1480] = 1,
    ACTIONS(215), 1,
      anon_sym_COMMA,
  [1484] = 1,
    ACTIONS(217), 1,
      anon_sym_GT,
  [1488] = 1,
    ACTIONS(219), 1,
      ts_builtin_sym_end,
  [1492] = 1,
    ACTIONS(221), 1,
      ts_builtin_sym_end,
  [1496] = 1,
    ACTIONS(223), 1,
      anon_sym_RBRACE,
  [1500] = 1,
    ACTIONS(225), 1,
      anon_sym_LPAREN,
  [1504] = 1,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
  [1508] = 1,
    ACTIONS(229), 1,
      ts_builtin_sym_end,
  [1512] = 1,
    ACTIONS(231), 1,
      anon_sym_COMMA,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 49,
  [SMALL_STATE(16)] = 96,
  [SMALL_STATE(17)] = 143,
  [SMALL_STATE(18)] = 215,
  [SMALL_STATE(19)] = 264,
  [SMALL_STATE(20)] = 333,
  [SMALL_STATE(21)] = 397,
  [SMALL_STATE(22)] = 457,
  [SMALL_STATE(23)] = 517,
  [SMALL_STATE(24)] = 577,
  [SMALL_STATE(25)] = 637,
  [SMALL_STATE(26)] = 679,
  [SMALL_STATE(27)] = 720,
  [SMALL_STATE(28)] = 763,
  [SMALL_STATE(29)] = 803,
  [SMALL_STATE(30)] = 843,
  [SMALL_STATE(31)] = 883,
  [SMALL_STATE(32)] = 923,
  [SMALL_STATE(33)] = 979,
  [SMALL_STATE(34)] = 1019,
  [SMALL_STATE(35)] = 1075,
  [SMALL_STATE(36)] = 1131,
  [SMALL_STATE(37)] = 1171,
  [SMALL_STATE(38)] = 1211,
  [SMALL_STATE(39)] = 1267,
  [SMALL_STATE(40)] = 1307,
  [SMALL_STATE(41)] = 1321,
  [SMALL_STATE(42)] = 1332,
  [SMALL_STATE(43)] = 1344,
  [SMALL_STATE(44)] = 1356,
  [SMALL_STATE(45)] = 1366,
  [SMALL_STATE(46)] = 1376,
  [SMALL_STATE(47)] = 1383,
  [SMALL_STATE(48)] = 1390,
  [SMALL_STATE(49)] = 1397,
  [SMALL_STATE(50)] = 1404,
  [SMALL_STATE(51)] = 1408,
  [SMALL_STATE(52)] = 1412,
  [SMALL_STATE(53)] = 1416,
  [SMALL_STATE(54)] = 1420,
  [SMALL_STATE(55)] = 1424,
  [SMALL_STATE(56)] = 1428,
  [SMALL_STATE(57)] = 1432,
  [SMALL_STATE(58)] = 1436,
  [SMALL_STATE(59)] = 1440,
  [SMALL_STATE(60)] = 1444,
  [SMALL_STATE(61)] = 1448,
  [SMALL_STATE(62)] = 1452,
  [SMALL_STATE(63)] = 1456,
  [SMALL_STATE(64)] = 1460,
  [SMALL_STATE(65)] = 1464,
  [SMALL_STATE(66)] = 1468,
  [SMALL_STATE(67)] = 1472,
  [SMALL_STATE(68)] = 1476,
  [SMALL_STATE(69)] = 1480,
  [SMALL_STATE(70)] = 1484,
  [SMALL_STATE(71)] = 1488,
  [SMALL_STATE(72)] = 1492,
  [SMALL_STATE(73)] = 1496,
  [SMALL_STATE(74)] = 1500,
  [SMALL_STATE(75)] = 1504,
  [SMALL_STATE(76)] = 1508,
  [SMALL_STATE(77)] = 1512,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_side_effects_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_side_effects_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_side_effects_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_side_effects_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_side_effects_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_side_effects_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_side_effects_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_side_effects_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_side_effects_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_side_effects_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_side_effects_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_side_effects, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 1, 0, 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 1, 0, 2),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 3, 0, 5),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key, 3, 0, 5),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant_value, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant_value, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 1, 0, 4),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 1, 0, 4),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alpha, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alpha, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 1, 0, 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 1, 0, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_attribute, 3, 0, 10),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key_attribute, 3, 0, 10),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3, 0, 15),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expr, 3, 0, 15),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_value, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_single_value, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 8),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 8),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_value, 5, 0, 19),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range_value, 5, 0, 19),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 9),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 9),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_values, 1, 0, 7),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_values, 1, 0, 7),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_free, 6, 0, 16),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_free, 6, 0, 16),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_swap, 6, 0, 18),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_swap, 6, 0, 18),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign, 3, 0, 6),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assign, 3, 0, 6),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_memory_side_effect, 1, 0, 1),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_memory_side_effect, 1, 0, 1),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expansion, 4, 0, 11),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expansion, 4, 0, 11),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_values, 3, 0, 14),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_values, 3, 0, 14),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_malloc, 6, 0, 16),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_malloc, 6, 0, 16),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_overflow, 6, 0, 17),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_overflow, 6, 0, 17),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [179] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_overflow_arg, 1, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_possibility, 1, 0, 12),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_possibility, 1, 0, 13),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_memory_summary, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_memory_summary, 3, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_overflow_func, 6, 0, 20),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_memory(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
